spring:
  application:
    name: mdas
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://pksuns.pakland.io:9000/dbgithub
    username: mdas
    password: 6%9%cqA#y#89rHS8
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: false
  profiles:
    active: dev
logging:
  level:
    root: INFO
  file:
    name: console_output.log
