name: Run unit tests

on: [pull_request]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: adopt
      - name: Run tests
        run: mvn test
      - name: Report test
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test results
          path: ${{ github.workspace }}/target/surefire-reports/*.xml
          reporter: java-junit
          working-directory: